[package]
name = "jankenstore"
version = "0.1.0"
edition = "2021"
authors = ["Martin Zheng <jszhengyq@gmail.com>"]
description = "Database operation helpers library"
readme = "README.md"
repository = "https://github.com/pandazy/jankenstore"
license = "MIT"
keywords = ["rust", "sqlite", "helpers", "database"]
categories = ["sqlite-database-helper"]

[dependencies]
anyhow = "1.0.*"
rusqlite = "0.32.*"

[dev-dependencies]
insta = "1.40.*"
