name: Release

on: 
  push:
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  archive:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "release.md"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  publish:
    needs: archive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo login $CARGO_REGISTRY_TOKEN
        cargo publish
        
